services:
    itmpostgres:
        image: postgres:latest
        container_name: itmpostgres
        environment:
            POSTGRES_USER: itm_ejemplo
            POSTGRES_PASSWORD: itm_password
            POSTGRES_DB: hotel
        volumes:
            - itm_postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    
    itmpgadmin:
        image:  dpage/pgadmin4:latest
        container_name: itmpgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: itm@itm.com
            PGADMIN_DEFAULT_PASSWORD: itm_pwd
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
            PGADMIN_LISTEN_PORT: 80
        depends_on:
            - itmpostgres
        ports:
            - 8088:80
        volumes:
            - itm_pgadmin_data:/var/lib/pgadmin
networks:
  default:
    driver: bridge

volumes:
    itm_postgres_data:
    itm_pgadmin_data:
